apiVersion: batch/v1
kind: Job
metadata:
  name: user-api-migrate
  namespace: fiapgames
spec:
  backoffLimit: 4
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: migrate
          image: user-games-fiap:latest
          imagePullPolicy: IfNotPresent
          args: ["--migrate"]
          envFrom:
            - configMapRef:
                name: user-api-config
            - secretRef:
                name: user-api-secret
