apiVersion: v1
kind: ConfigMap
metadata:
  name: user-api-config
  namespace: fiapgames
  labels:
    app: user-api
data:
  ASPNETCORE_ENVIRONMENT: "Production"
  Database__MigrateOnStartup: "false"
  RabbitMq__HostName: "rabbitmq"
  RabbitMq__Port: "5672"
  RabbitMq__VirtualHost: "/"
  Jwt__Issuer: "User.Games.Fiap"
  Jwt__Audience: "Games.Fiap"
  Jwt__AccessTokenMinutes: "15"
  Jwt__RefreshTokenDays: "7"
